apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jenkins-server
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
        namespace: jenkins-001
      - cluster: backend-preprod
        url: https://kubernetes.default.svc
        namespace: jenkins-003
      - cluster: frontend-preprod
        url: https://kubernetes.default.svc
        namespace: jenkins-004
  template:
    metadata:
      name: '{{cluster}}-jenkins-server'
    spec:
      project: default
      source:
        repoURL: https://github.com/lightyear0/argocd-demo.git
        targetRevision: HEAD
        path: helm/jenkins
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'